"""Validate the QMD collection files generated by kb-bootstrap."""

from __future__ import annotations

import re
from pathlib import Path
from typing import List, Tuple, Union


NAME_PATTERN = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*$")


def _collection_values(path: Path) -> Tuple[str, List[str], List[str]]:
    """Read the small YAML subset used by generated collection files."""
    name = ""
    paths: List[str] = []
    exclude: List[str] = []
    section = ""

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        stripped = raw_line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if not raw_line.startswith((" ", "\t")) and ":" in stripped:
            key, value = stripped.split(":", 1)
            section = key
            value = value.strip().strip('"').strip("'")
            if key == "name":
                name = value
            continue
        if stripped.startswith("-"):
            value = stripped[1:].strip().strip('"').strip("'")
            if section == "paths":
                paths.append(value)
            elif section == "exclude":
                exclude.append(value)

    return name, paths, exclude


def validate_qmd_collections(
    project_root: Union[str, Path],
) -> Tuple[str, bool]:
    """Validate collection syntax and ensure every configured path exists."""
    root = Path(project_root)
    collections_dir = root / "qmd" / "collections"
    lines = ["=== QMD Collection Validation ==="]
    errors: List[str] = []

    if not collections_dir.is_dir():
        errors.append("Missing qmd/collections directory")
        collection_files: List[Path] = []
    else:
        collection_files = sorted(collections_dir.glob("*.yaml"))
        if not collection_files:
            errors.append("No qmd/collections/*.yaml files found")

    seen_names = set()
    for collection in collection_files:
        try:
            name, paths, _ = _collection_values(collection)
        except (OSError, UnicodeError) as error:
            errors.append(f"{collection.name}: cannot read collection ({error})")
            continue

        if not name or not NAME_PATTERN.fullmatch(name):
            errors.append(f"{collection.name}: missing or invalid name")
        elif name in seen_names:
            errors.append(f"{collection.name}: duplicate collection name '{name}'")
        else:
            seen_names.add(name)

        if not paths:
            errors.append(f"{collection.name}: paths must contain at least one entry")

        for configured_path in paths:
            if not configured_path or "\x00" in configured_path:
                errors.append(f"{collection.name}: invalid path entry")
                continue
            if any(character in configured_path for character in "*?["):
                errors.append(
                    f"{collection.name}: glob patterns are not supported in paths: {configured_path}"
                )
                continue
            resolved = (collection.parent / configured_path).resolve()
            if not resolved.exists():
                errors.append(
                    f"{collection.name}: configured path does not exist: {configured_path}"
                )

    lines.append(f"Collections: {len(collection_files)}")
    if errors:
        lines.append(f"ERRORS ({len(errors)}):")
        lines.extend(f"   - {error}" for error in errors)
    else:
        lines.append("ERRORS: 0")
    lines.extend(
        [
            "",
            "Next: run `qmd update`, then smoke-test `qmd search` for each collection.",
        ]
    )
    return "\n".join(lines), not errors
